spring:
  application:
    name: demo
  temporal:
    connection:
      target: 127.0.0.1:7233
      target.namespace: default
    workers:
      - task-queue: TeamTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 10
      max-threads: 10
    workers-auto-discovery:
      packages: com.temporal.example.demo.temporal
server:
  forward-headers-strategy: framework
  port: 7888
